### ISSUE TITLE
Clear up home page graphs

### ISSUE THREAD

**Issue by Alex-Rice** [BandToThePole/WebSite#12]
I plan to take out some graphs from home page so that the home page has minimal data and most the data is left for the graphs page. Will leave the heart rates graph and add in a minimal map unless anyone objects

**Comment by thomasdenney** [comment]
Take a look at bandtothepole.azurewebsites.net if you want to get an idea what the UCL team did; I think we have slightly less ATM.

**Comment by Alex-Rice** [comment]
They seem to have everything on one page. Since we have a separate graphs page I feel it makes sense to keep the home screen uncluttered
