### ISSUE TITLE
Graceful degradation

### ISSUE THREAD

**Issue by thomasdenney** [BandToThePole/WebSite#13]
If we do not receive a good response for the API request (e.g. 500 Internal Server) we should probably display some error on the web page.

**Comment by gpirindev** [comment]
I've added an error div in the home, data and graph pages. However, the error is displayed a minute later and I don't know why.

**Comment by Alex-Rice** [comment]
You've got req.status == 500 but the status will be in the response not the request

**Comment by gpirindev** [comment]
With XMLHttpRequest the result's status and contents are available in the request object when the transaction is completed according to https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest
So I suppose it takes a while to complete the transaction.

**Comment by Alex-Rice** [comment]
Are you checking the status in the callback or before the request is sent

**Comment by gpirindev** [comment]
When testing in on my computer, running the server locally, the request takes a long time until it changes it state to DONE. However, it works well on the website and displays the error almost instantly.
