### ISSUE TITLE
Show locations as map rather than list

### ISSUE THREAD

**Issue by thomasdenney** [BandToThePole/WebSite#2]

**Comment by Alex-Rice** [comment]
Looked a little into this, Microsoft has suggest we use bing maps, however bing maps enforces a mercator projection which stops at 85 degrees latitude. Maybe we should look at other option, possibly even a static image that we can draw over

**Comment by thomasdenney** [comment]
Does Google Maps do anything more sensible?

**Comment by Alex-Rice** [comment]
Possibly. I found a page about custom map projections but it looks like you have to provide a picture and a function from longlat to coordinates, so unless someone has done the code for a polar projection it doesn't look much easier

**Comment by thomasdenney** [comment]
OK, I think embedded Google/Bing Maps is probably the best way to go then.

**Comment by Alex-Rice** [comment]
https://github.com/nasa-gibs/gibs-web-examples maybe use something in here?

**Comment by Alex-Rice** [comment]
This looks surprisingly simple and open source, might have a play around with it at some point

**Comment by Alex-Rice** [comment]
http://openlayers.org/ this looks like something we could use, there is an example of it in the link above and it appears it has functionality to draw polygons on the map. Maybe we can discuss this more in the meeting
