### ISSUE TITLE
Don't store passwords in plain text

### ISSUE THREAD

**Issue by thomasdenney** [BandToThePole/WebSite#4]
This isn't really important seen as we only need to use authentication for the app that James is using, but it isn't very secure.

**Comment by Alex-Rice** [comment]
Should i just store a hash of the password. No one should have access to the database but it shouldn't be hard to change

**Comment by thomasdenney** [comment]
@Alex-Rice Yeah that sounds fine. Make sure you use a secure hashing algorithm (SHA-X, where X is big).

**Comment by Alex-Rice** [comment]
Should passwords now be sent as a hash? or still sent plain

**Comment by thomasdenney** [comment]
Sent plain, sotred as hash.

**Comment by Alex-Rice** [comment]
ok

**Comment by Alex-Rice** [comment]
I've read it's better to use a slower encryption to store passwords, are we worried about this or will sha3 be fine

**Comment by thomasdenney** [comment]
https://crackstation.net/hashing-security.htm this covers the topic in full. SHA-3 should be fine.

**Comment by Alex-Rice** [comment]
It also recommends using a slower hashing function, I will switch to using bcrypt

**Comment by Alex-Rice** [comment]
This is now done, Old usernames have been removed and must be added again with the command line tool to properly set them up
