### ISSUE TITLE
Calories/distance scatter plot

### ISSUE THREAD

**Issue by thomasdenney** [BandToThePole/WebSite#8]

**Comment by gpirindev** [comment]
Graphs made as scatter plots.

**Comment by gpirindev** [comment]
Should we change the graphs to scatter plots on the app as well?

**Comment by thomasdenney** [comment]
Sorry, I should have been clearer: the calorie per day and distance per day graphs should not be scatter plots - they should be bar charts. However, I think it would be interesting to add a calorie per day vs distance per day chart separately.

**Comment by gpirindev** [comment]
I have deleted my commit. To get this right, are you suggesting that we add scatter plots (calorie per day and distance per day) after the bar charts?

**Comment by thomasdenney** [comment]
It's a single scatter plot I want to do: calories on one axis, distance on the other
